services:
  backend:
    container_name: fabric-backend
    volumes:
      - ./app:/app/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MSSQL_SERVER: "192.168.10.219,1433"
      MSSQL_DATABASE: "styxdev"
      MSSQL_USERNAME: "SA"
      MSSQL_PASSWORD: "YourStrong@Passw0rd"
    restart: always
    networks:
      - fabric-net

networks:
  fabric-net:
    driver: bridge
